### ISSUE TITLE
How to use Hatchej (non-Spotify employee)

### ISSUE THREAD

**Issue by BryanRansil** [menny/bazel-leaf#4]
Firstly, thanks for publishing this repo! It looks incredibly useful for some projects I'm working on.
When I complete importing the project, android studio can't find hatchej. I'm assuming hatchej isn't public yet, since I don't see the project on github. Are there plans to make it public? If not, would there be problems if I undid commit d3c03288ca6648019d02ace61cffc07f70456ceb?

**Comment by menny** [comment]
It seems that this project is falling behind my local copy. I'll clean it up and push.

**Comment by BryanRansil** [comment]
Glad to hear! Do you happen to know when you'll be able to do that?

**Comment by menny** [comment]
finally... it's there.

**Comment by BryanRansil** [comment]
Thank you so much! Will look forward to using this :smile:
